### Register
POST http://localhost:8000/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "name": "admin",
  "email": "test@example.com",
  "password": "password",
  "password_confirmation": "password"
}